version: "3"
services:
  # Multistate build
  MyApp:
    image: myapp:latest
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    ports:
      - "3000:80"

# docker build -t narongsakjaro/crudapi-golang -f multistage.Dockerfile .